name: definitely_not_tooltip
description: A custom tooltip plugin for Flutter.
version: 0.22.0

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
